# Generated by Django 5.0.4 on 2024-04-24 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='galeria-projecto')),
                ('orden', models.IntegerField(default=1)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('projecto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.projecto')),
            ],
            options={
                'db_table': 'tbl_projecto_imagen',
            },
        ),
    ]
