# Generated by Django 5.0.4 on 2024-04-25 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_projectoimagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectoimagen',
            options={'verbose_name': 'Imagen del Projecto', 'verbose_name_plural': 'Imagenes del Projecto'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='CategoriaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='galeria-categoria')),
                ('orden', models.IntegerField(default=1)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.categoria')),
            ],
            options={
                'verbose_name_plural': 'Imagenes de las Categorias',
                'db_table': 'tbl_categoria_imagen',
            },
        ),
    ]
