# Generated by Django 5.0.4 on 2024-04-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_projectoimagen_options_categoria_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('profesion', models.CharField(max_length=250)),
                ('comentario', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('facebook', models.CharField(max_length=250, null=True)),
                ('twitter', models.CharField(max_length=250, null=True)),
                ('linkedin', models.CharField(max_length=250, null=True)),
                ('instagram', models.CharField(max_length=250, null=True)),
                ('youtube', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
