# Generated by Django 5.0.4 on 2024-04-25 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_informacionindex_clienteimagen_equipoimagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'verbose_name': 'Euipo'},
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='tbl_cliente',
        ),
        migrations.AlterModelTable(
            name='equipo',
            table='tbl_equipo',
        ),
        migrations.AlterModelTable(
            name='informacionindex',
            table='tbl_info_index',
        ),
    ]
